logto-io/connectors

README.md

Update README file.
No needed.

docs: reademe

---

packages/connector-azuread/src/index.ts

should init confidential client with real-time config.
N/A

chore: should init confidential client with real time config

---

packages/connector-azuread/src/constant.ts
packages/connector-facebook/src/constant.ts
packages/connector-github/src/constant.ts
packages/connector-google/src/constant.ts
packages/connector-kakao/src/constant.ts

Update connectors description to avoid using words like 'the biggest', 'the most popular', etc.

chore: update connectors description

---

packages/connector-alipay-native/package.json
packages/connector-alipay-web/package.json
packages/connector-aliyun-dm/package.json
packages/connector-aliyun-sms/package.json
packages/connector-apple/package.json
packages/connector-azuread/package.json
packages/connector-facebook/package.json
packages/connector-github/package.json
packages/connector-google/package.json
packages/connector-kakao/package.json
packages/connector-mock-email/package.json
packages/connector-mock-sms/package.json
packages/connector-mock-social/package.json
packages/connector-sendgrid-email/package.json
packages/connector-smtp/package.json
packages/connector-twilio-sms/package.json
packages/connector-wechat-native/package.json
packages/connector-wechat-web/package.json
pnpm-lock.yaml

Bump `connector-core` to 1.0.0-beta.9
N/A

chore: bump to connector-core 1.0.0-beta.9

---

packages/connector-alipay-web/README.md
packages/connector-alipay-web/docs/config-template.json
packages/connector-alipay-web/src/constant.ts
packages/connector-alipay-web/src/index.ts
packages/connector-alipay-web/src/types.ts
packages/connector-alipay-web/src/utils.ts

1. Align Alipay web readme and code.
2. Stick to lowercase encodings (prefer 'gbk'/'utf8' over 'GBK'/'UTF8').
Passed UTs and tested locally.

chore: align alipay web readme and code, and stick to lowercase encodings

---

packages/connector-alipay-web/package.json
packages/connector-alipay-web/src/constant.ts
packages/connector-alipay-web/src/index.test.ts
packages/connector-alipay-web/src/index.ts
packages/connector-alipay-web/src/types.ts
pnpm-lock.yaml

Use @logto/core-kit Zod fallback() instead of zod.transform().
N/A

chore: use @logto/core-kit zod fallback() instead of zod.transform()

---

lerna.json

sync root version with packages
N/A

chore: fix root version

---

packages/connector-alipay-native/src/index.ts
packages/connector-alipay-web/src/index.ts
packages/connector-aliyun-dm/src/index.ts
packages/connector-aliyun-sms/src/index.ts
packages/connector-azuread/src/index.ts
packages/connector-discord/src/index.ts
packages/connector-facebook/src/index.ts
packages/connector-github/src/index.ts
packages/connector-google/src/index.ts
packages/connector-kakao/src/index.ts
packages/connector-naver/src/index.ts
packages/connector-wechat-native/src/index.ts
packages/connector-wechat-web/src/index.ts

data in ConnectorError should be ZodError to utilize zodErrorMessageFormatter
N/A

chore: data in ConnectorError should be ZodError to utilize zodErrorMessageFormatter

---

.github/CONTRIBUTING.md
README.md

connector contribution guidelines.
N/A

docs: connector contribution guidelines

---

packages/connector-aliyun-dm/src/utils.test.ts
packages/connector-aliyun-sms/src/utils.test.ts

chore: fix typo

---

packages/connector-aliyun-dm/docs/config-template.json
packages/connector-aliyun-sms/docs/config-template.json
packages/connector-mock-email/docs/config-template.json
packages/connector-mock-sms/docs/config-template.json
packages/connector-sendgrid-email/docs/config-template.json
packages/connector-smtp/docs/config-template.json
packages/connector-twilio-sms/docs/config-template.json

Add forgot password and continue templates for sms and email.
/

feat: add forgot password and continue templates for sms and email

---

packages/connector-aliyun-dm/README.md
packages/connector-aliyun-sms/README.md
packages/connector-sendgrid-email/README.md
packages/connector-smtp/README.md
packages/connector-twilio-sms/README.md

update passwordless connector readme
N/A

chore: update passwordless connectors readme

---

packages/connector-mock-social/src/index.ts

update mock social connector to support email and phone number in UserInfo. For integration test use.
N/A

refactor(test): update mock social connector

---

packages/connector-aliyun-dm/README.md
packages/connector-aliyun-dm/src/index.test.ts
packages/connector-aliyun-dm/src/mock.ts
packages/connector-aliyun-dm/src/types.test.ts
packages/connector-aliyun-dm/src/types.ts
packages/connector-aliyun-sms/README.md
packages/connector-aliyun-sms/src/index.test.ts
packages/connector-aliyun-sms/src/mock.ts
packages/connector-aliyun-sms/src/types.ts
packages/connector-sendgrid-email/README.md
packages/connector-sendgrid-email/src/types.ts
packages/connector-smtp/src/mock.ts
packages/connector-smtp/src/types.ts
packages/connector-tencent-sms/README.md
packages/connector-tencent-sms/src/index.test.ts
packages/connector-tencent-sms/src/mock.ts
packages/connector-tencent-sms/src/schema.ts
packages/connector-twilio-sms/README.md
packages/connector-twilio-sms/src/types.ts

add template existence check (by usageType) to passwordless connectors.
Added UTs to test this.

feat: add template existence check to passwordless connectors

---

packages/connector-aliyun-dm/README.md
packages/connector-aliyun-dm/docs/config-template.json

Signed-off-by: kentio <13550898+kentio@users.noreply.github.com>

fix(aliyun dm): fix config-template.json of aliyun(dm)

---

templates/sync-from-current.js
templates/sync-to-current.js

fix: filter out DS_Store files

---

packages/connector-oauth2/README.md
packages/connector-oauth2/docs/config-template.json

update OAuth connector readme for `tokenEndpointResponseType` usage
N/A

chore: update OAuth connector readme for `tokenEndpointResponseType` usage

---

.github/workflows/publish.yml

add `git config` since we ignored `package.json` in source control
after merge

ci: fix public workflow

---

packages/connector-oidc/src/constant.ts

fix OIDC dark logo broken.
Tested with AC dark mode locally.

fix: fix OIDC dark logo

---

packages/connector-oidc/src/index.ts
packages/connector-oidc/src/utils.ts

Should provide `redirectUri` for token requests.

fix: fix OIDC bad request error

---

packages/connector-apple/README.md
packages/connector-apple/package.extend.json
packages/connector-apple/src/index.test.ts
packages/connector-apple/src/index.ts
packages/connector-apple/src/utils.ts
packages/connector-oidc/src/utils.ts
pnpm-lock.yaml

enabled support on nonce validation for apple connector
Tested locally and it works well with random generated `nonce`.

feat: enabled support on nonce validation for apple connector

---

packages/connector-oauth2/src/utils.ts
packages/connector-oidc/src/index.ts
packages/connector-oidc/src/utils.ts

expose as much error info as possible.
CI.

chore: expose as much error info as possible

---

packages/connector-tencent-sms/src/http.ts

Fix the wrong month value in date, which ends up with a signature issue

fix: signature issue caused by wrong month in date

---

packages/connector-alipay-native/README.md
packages/connector-alipay-web/README.md
packages/connector-azuread/README.md
packages/connector-discord/README.md
packages/connector-facebook/README.md
packages/connector-feishu-web/README.md
packages/connector-github/README.md
packages/connector-google/README.md
packages/connector-kakao/README.md
packages/connector-naver/README.md

update the way of setting redirect uri.
N/A

chore: update the way of setting redirect uri

---

templates/sync-to-current.js

fix the merge of arrays logic.

fix: allow array merging in `package.json`

---

packages/connector-aliyun-dm/README.md
packages/connector-aliyun-dm/src/mock.ts
packages/connector-aliyun-dm/src/types.ts
packages/connector-aliyun-sms/README.md
packages/connector-aliyun-sms/src/mock.ts
packages/connector-aliyun-sms/src/types.ts
packages/connector-aws-ses/README.md
packages/connector-aws-ses/docs/config-template.json
packages/connector-mock-email/docs/config-template.json
packages/connector-mock-sms/docs/config-template.json
packages/connector-sendgrid-email/README.md
packages/connector-sendgrid-email/docs/config-template.json
packages/connector-sendgrid-email/src/types.ts
packages/connector-smtp/README.md
packages/connector-smtp/docs/config-template.json
packages/connector-smtp/src/mock.ts
packages/connector-smtp/src/types.ts
packages/connector-tencent-sms/README.md
packages/connector-tencent-sms/docs/config-template.json
packages/connector-tencent-sms/src/mock.ts
packages/connector-tencent-sms/src/schema.ts
packages/connector-twilio-sms/README.md
packages/connector-twilio-sms/docs/config-template.json
packages/connector-twilio-sms/src/types.ts

remove "Continue" template in code and readme since no more continue template is needed.
N/A

chore: remove Continue template in code and readme

---

packages/connector-oauth2/README.md
packages/connector-oauth2/docs/config-template.json
packages/connector-oauth2/package.extend.json
packages/connector-oauth2/src/constant.ts
packages/connector-oauth2/src/index.ts
packages/connector-oauth2/src/types.ts
packages/connector-oauth2/src/utils.ts
packages/connector-oidc/README.md
packages/connector-oidc/docs/config-template.json
packages/connector-oidc/package.extend.json
packages/connector-oidc/src/constant.ts
packages/connector-oidc/src/index.ts
packages/connector-oidc/src/types.ts
packages/connector-oidc/src/utils.ts
pnpm-lock.yaml

1. use pick instead of omit for oidc/oauth2 connector
2. update README configuration guide
Locally tested both OIDC and oauth2 connectors with all scopes and flows/grant types.

refactor: use pick instead of omit for oidc/oauth2 connector

---

.changeset/pretty-wombats-deny.md
packages/connector-alipay-native/src/index.test.ts
packages/connector-alipay-web/src/index.test.ts
packages/connector-apple/src/index.test.ts
packages/connector-discord/src/index.test.ts
packages/connector-facebook/src/index.test.ts
packages/connector-feishu-web/src/index.test.ts
packages/connector-github/src/index.test.ts
packages/connector-google/src/index.test.ts
packages/connector-kakao/src/index.test.ts
packages/connector-naver/src/index.test.ts
packages/connector-wechat-native/src/index.test.ts
packages/connector-wechat-web/src/index.test.ts
pnpm-lock.yaml
templates/package.json

update connectors @logto/connector-kit version to 1.0.0-beta.33
N/A

chore: update connectors @logto/connector-kit version to 1.0.0-beta.33

---

.changeset/green-bees-cross.md

add changeset for saml connector
N/A

chore: add changeset for saml connector

---

packages/connector-saml/README.md

Fix typo in readme and add "required" tag for required configs.
N/A

chore: fix saml readme

---

packages/connector-saml/README.md

replace `<br/>` with newlines in the SAML connector readme
N/A

chore: replace br with newlines in the SAML connector README

---

.changeset/green-humans-smoke.md
packages/connector-aliyun-dm/src/utils.test.ts
packages/connector-aliyun-dm/src/utils.ts
packages/connector-aliyun-sms/src/utils.test.ts
packages/connector-aliyun-sms/src/utils.ts

Update the format of the parameter passed into `got.post` to fit the change of got v12.

fix: update the format of input parameter to fit got v12

---

.changeset/thin-sloths-breathe.md
packages/connector-smtp/package.extend.json
packages/connector-smtp/src/types.ts
pnpm-lock.yaml

remove SMTP connector dependency on @logto/shared.

fix: remove SMTP connector dependency on @logto/shared

---

.changeset/seven-bobcats-fail.md
packages/connector-saml/README.md
packages/connector-saml/src/index.ts
packages/connector-saml/src/types.ts
packages/connector-saml/src/utils.ts

1. specify SAML config `nameIDFormat`, use enum type instead of string array (since only the first element in a non-empty string array is concerned)
2. Update the way of exposing `samlify` lib error messages.

refactor!: specify SAML config nameIDFormat

---

.changeset/seven-bobcats-fail.md

Temporarily remove SAML `nameIDFormat` type breaking change changeset.
N/A

chore: remove saml nameIDFormat changeset

---

packages/connector-saml/README.md

remove preprocess notice on multiple line text.

fix: remove preprocess notice on multiple line text

---

packages/connector-saml/src/constant.ts

update nameIDFormat formItems since it has been updated to be enum type.

fix: update nameIDFormat formItems

---

packages/connector-oidc/README.md
packages/connector-oidc/docs/config-template.json
packages/connector-oidc/package.extend.json
packages/connector-oidc/src/index.ts
packages/connector-oidc/src/types.test.ts
packages/connector-oidc/src/types.ts
packages/connector-oidc/src/utils.ts
pnpm-lock.yaml

remove implicit flow and hybrid flow to ensure security

feat!: remove implicit flow and hybrid flow to ensure security

---

packages/connector-saml/src/constant.ts

update SAML connector ACS URL form item label and add desc.

chore: update SAML connector acs url form item label and desc

---

.changeset/fresh-buckets-heal.md

force bump for the new release
/

chore: bump version to upgrade connector kit

---

packages/connector-apple/docs/config-template.json
packages/connector-apple/src/constant.ts
packages/connector-azuread/docs/config-template.json
packages/connector-azuread/src/constant.ts
packages/connector-facebook/docs/config-template.json
packages/connector-facebook/src/constant.ts

fb/aad/apple connectors use form view config
Will add a changeset for all eligible connectors after the migration to form view is finished

feat: fb/aad/apple connectors use form view config

---

packages/connector-kakao/docs/config-template.json
packages/connector-kakao/src/constant.ts
packages/connector-naver/docs/config-template.json
packages/connector-naver/src/constant.ts

kakao/naver connectors use form view config

feat: kakao/naver connectors use form view config

---

packages/connector-alipay-native/docs/config-template.json
packages/connector-alipay-native/src/constant.ts
packages/connector-alipay-web/docs/config-template.json
packages/connector-alipay-web/src/constant.ts

alipay connectors use form view config

feat: alipay connectors use form view config

---

packages/connector-wechat-native/docs/config-template.json
packages/connector-wechat-native/src/constant.ts
packages/connector-wechat-web/docs/config-template.json
packages/connector-wechat-web/src/constant.ts

wechat connectors use form view config

feat: wechat connectors use form view config

---

packages/connector-feishu-web/docs/config-template.json
packages/connector-feishu-web/src/constant.ts

feishu web connector use form view config

feat: feishu web connector use form view config

---

packages/connector-discord/docs/config-template.json
packages/connector-discord/src/constant.ts

Update discord connector to enforce Form view configuration.

feat: discord use form view config

---

packages/connector-github/docs/config-template.json
packages/connector-github/src/constant.ts
packages/connector-google/docs/config-template.json
packages/connector-google/src/constant.ts

Update Google and GitHub connector to enforce Form view configuration.

feat: github/google connector use form view config

---

packages/connector-aliyun-dm/README.md
packages/connector-aliyun-sms/README.md
packages/connector-apple/README.md
packages/connector-aws-ses/README.md
packages/connector-azuread/README.md
packages/connector-facebook/README.md
packages/connector-github/README.md
packages/connector-google/README.md
packages/connector-oauth2/README.md
packages/connector-oidc/README.md
packages/connector-saml/README.md
packages/connector-sendgrid-email/README.md
packages/connector-smtp/README.md
packages/connector-tencent-sms/README.md
packages/connector-twilio-sms/README.md
packages/connector-wechat-native/README.md
packages/connector-wechat-web/README.md

1. Remove config JSON guide in connectors' readme files since all connectors' configuration has been migrated to form view.
2. Remove some rarely used zh-CN contents from readme files for better display.
Tested locallt.
OR
Will add a changeset for all connectors.

chore: remove json-related and some zh-CN contents from readme

---

.changeset/witty-coins-end.md

Add connectors changeset (update to form view).
N/A

chore: add connectors changeset (update to form view)

---

.changeset/lazy-ways-boil.md
packages/connector-logto-email/README.md
packages/connector-logto-email/logo-dark.svg
packages/connector-logto-email/logo.svg
packages/connector-logto-email/package.extend.json
packages/connector-logto-email/src/constant.ts
packages/connector-logto-email/src/grant-access-token.test.ts
packages/connector-logto-email/src/grant-access-token.ts
packages/connector-logto-email/src/index.test.ts
packages/connector-logto-email/src/index.ts
packages/connector-logto-email/src/mock.ts
packages/connector-logto-email/src/types.ts
pnpm-lock.yaml

Add logto email for demo.
Will optimize the access token cache in the future (LOG-5693)
Local tested and UTs
OR

feat: add logto email

---

.changeset/short-icons-report.md
packages/connector-aliyun-dm/README.md
packages/connector-aliyun-dm/src/constant.ts
packages/connector-aliyun-dm/src/mock.ts
packages/connector-aliyun-dm/src/types.ts
packages/connector-aliyun-sms/README.md
packages/connector-aliyun-sms/src/constant.ts
packages/connector-aliyun-sms/src/mock.ts
packages/connector-aliyun-sms/src/types.ts
packages/connector-aws-ses/README.md
packages/connector-aws-ses/src/constant.ts
packages/connector-aws-ses/src/mock.ts
packages/connector-aws-ses/src/types.ts
packages/connector-mock-email-alternative/docs/config-template.json
packages/connector-mock-email/docs/config-template.json
packages/connector-mock-sms/docs/config-template.json
packages/connector-sendgrid-email/README.md
packages/connector-sendgrid-email/src/constant.ts
packages/connector-sendgrid-email/src/types.ts
packages/connector-smtp/README.md
packages/connector-smtp/src/constant.ts
packages/connector-smtp/src/mock.ts
packages/connector-smtp/src/types.ts
packages/connector-tencent-sms/README.md
packages/connector-tencent-sms/src/constant.ts
packages/connector-tencent-sms/src/mock.ts
packages/connector-tencent-sms/src/schema.ts
packages/connector-twilio-sms/README.md
packages/connector-twilio-sms/src/constant.ts
packages/connector-twilio-sms/src/types.ts

update passwordless connector template
UTs.
OR

refactor: update passwordless connector template

---

packages/connector-azuread/README.md

update per [docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration)

chore: update microsoft AzureAD README.md

---

.changeset/quiet-goats-approve.md
packages/connector-azuread/README.md

Azure AD name, description, logo and readme have been updated in the previous two PRs:
1. https://github.com/logto-io/connectors/pull/134
2. https://github.com/logto-io/connectors/pull/141
Need to publish these changes so that they can kick in.
OR

chore: update Azure AD name, description, logo and readme

---

.changeset/silly-files-compete.md
packages/connector-oauth2/src/index.test.ts
packages/connector-oauth2/src/mock.ts
packages/connector-oidc/src/index.test.ts
packages/connector-oidc/src/mock.ts

add UTs for OIDC and OAuth connector happy path.
UTs.
OR

chore: add UTs for OIDC and OAuth connector happy path

---

.changeset/gorgeous-hairs-confess.md
packages/connector-oauth2/README.md
packages/connector-oidc/README.md

update oidc and oauth connector readme
N/A
OR

docs: update oidc and oauth connector readme
